import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import {Button,Card,Field} from '../components/Ui';

export function Providers(){
  const [rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const [form,setForm]=useState({slug:'',kind:'openai-compatible',baseUrl:'',apiKey:''});
  const load=()=>api<any[]>('/api/admin/providers').then(setRows);
  useEffect(()=>{load()},[]);
  const action=async(key:string,work:()=>Promise<any>)=>{setBusy(key);setMessage('');try{const value=await work();setMessage(typeof value==='string'?value:'Operation completed');await load()}catch(error){setMessage(error instanceof Error?error.message:'Operation failed')}finally{setBusy('')}};
  return <><h1>Providers</h1><Card><h2>Add provider</h2><div className="formrow"><Field label="Slug"><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></Field><Field label="Kind"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option>openai-compatible</option><option>openai</option><option>anthropic</option><option>gemini</option><option>xai</option><option>deepseek</option><option>ollama</option></select></Field><Field label="Base URL"><input value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})}/></Field><Field label="API key"><input type="password" value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value})}/></Field></div><Button onClick={()=>action('add',async()=>{await api('/api/admin/providers',{method:'POST',body:JSON.stringify({...form,displayName:form.slug})});setForm({slug:'',kind:'openai-compatible',baseUrl:'',apiKey:''});return 'Provider added'})} disabled={busy==='add'}>Add</Button></Card>{message&&<Card>{message}</Card>}<div className="stack">{rows.map(p=><Card key={p.id}><div className="row"><div><b>{p.display_name}</b><small>{p.slug} · {p.kind} · {p.enabled?'enabled':'disabled'}</small><small>{p.base_url}</small><small>Verification: {p.verified_count}/{p.model_count} verified{p.unavailable_count?` · ${p.unavailable_count} unavailable`:''}</small></div><div><Button disabled={!!busy} onClick={()=>action(`test-${p.slug}`,async()=>{const result=await api<any>(`/api/admin/providers/${p.slug}/test`,{method:'POST'});return result.ok?`Healthy (${Math.round(result.latencyMs)} ms)`:`Unhealthy: ${result.detail??'provider check failed'}`})}>Health</Button> <Button disabled={!!busy} onClick={()=>action(`discover-${p.slug}`,async()=>{const result=await api<any[]>(`/api/admin/providers/${p.slug}/discover`,{method:'POST'});return `Discovered ${result.length} models`})}>Discover</Button> <Button disabled={!!busy} onClick={()=>action(`verify-${p.slug}`,async()=>{const result=await api<any[]>(`/api/admin/providers/${p.slug}/verify`,{method:'POST'});return `Verified ${result.length} models`})}>Verify Models</Button></div></div></Card>)}</div></>;
}
